### PR TITLE
RecyclerView

### PR DESCRIPTION
**Pull request by noman2002**
Brief description of RecyclerView. 
Given as audition task.

### CODE REVIEW

**Comment by danishjamal104** [comment]
### Make below two changes

1. Try reframing the sentences. 
    As of my review, most of the contents seem that they are copied from [geeks for geeks]. (https://www.geeksforgeeks.org/android-recyclerview/) and [this](https://raw.githubusercontent.com/kallemshivashekarreddy/Recycler-View/master/RecyclerView) repo.

2. Move the RecyclerView.md to a new folder named RecyclerView instead of directly putting in the Android Development folder.

**Comment by danishjamal104** [comment]
Move recycler view folder inside android development folder.

**Comment by noman2002** [comment]
After making the changes do i have to create a new PR

**Comment by danishjamal104** [comment]
no.

**Comment by danishjamal104** [comment]
Just change the path of your readme file. Move it to this path  developer-roadmap/Android Development/RecyclerView/readme.md, and commit the changes

**Comment by noman2002** [comment]
I have committed the suggested changes. you can check it now.

**Review by danishjamal104 — APPROVED** [review]

**Pull request merged**
