### PR TITLE
Data Analyst resources added

### PR DESCRIPTION
**Pull request by ashwanisng**
all the easily available resources added

### CODE REVIEW

**Comment by siayush** [comment]
Add more resources regarding each topic.

**Comment by ashwanisng** [comment]
added more resources

**Comment by ashwanisng** [comment]
updated the resources

**Comment by siayush** [comment]
Great Work @ashwanisng

**Comment by siayush** [comment]
Do one thing remove the unnecessary image files.

**Comment by ashwanisng** [comment]
unnecessary image files deleted

**Pull request merged**
